# Generated by Django 3.2.2 on 2021-08-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='body',
            new_name='description',
        ),
    ]
